# Generated by Django 5.2.8 on 2025-11-19 20:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedPrivateLobbyStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lobby_id', models.UUIDField(db_index=True)),
                ('total_participants', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'archived_private_lobby_stats',
                'ordering': ['-expired_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivateLobby',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('creator_token', models.CharField(db_index=True, help_text='Anon token of creator', max_length=64)),
                ('max_participants', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('full', 'Full'), ('expired', 'Expired')], db_index=True, default='active', max_length=10)),
                ('lobby_code', models.CharField(db_index=True, help_text='Short shareable code', max_length=8, unique=True)),
            ],
            options={
                'db_table': 'private_lobbies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='private_lob_status_01b358_idx'), models.Index(fields=['creator_token', 'created_at'], name='private_lob_creator_e6feeb_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrivateLobbyParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anon_token', models.CharField(db_index=True, help_text='SHA256(IP+UA+salt) for abuse prevention', max_length=64)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='private_lobby.privatelobby')),
            ],
            options={
                'db_table': 'private_lobby_participants',
                'ordering': ['joined_at'],
                'constraints': [models.UniqueConstraint(fields=('lobby', 'anon_token'), name='unique_participant_per_private_lobby')],
            },
        ),
    ]
