# Generated by Django 5.2.8 on 2025-11-19 20:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedLobbyStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lobby_id', models.UUIDField(db_index=True)),
                ('game', models.CharField(choices=[('valorant', 'Valorant'), ('csgo', 'CS:GO'), ('apex', 'Apex Legends'), ('lol', 'League of Legends')], max_length=20)),
                ('rank', models.CharField(max_length=20)),
                ('vibe', models.CharField(choices=[('serious', 'Serious'), ('chill', 'Chill'), ('competitive', 'Competitive'), ('casual', 'Casual'), ('tryhard', 'Tryhard')], max_length=20)),
                ('total_participants', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mic_required', models.BooleanField(default=False)),
                ('region', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'archived_lobby_stats',
                'ordering': ['-expired_at'],
                'indexes': [models.Index(fields=['game', 'expired_at'], name='archived_lo_game_21ed3a_idx'), models.Index(fields=['created_at'], name='archived_lo_created_d92232_idx')],
            },
        ),
        migrations.CreateModel(
            name='PublicLobby',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('game', models.CharField(choices=[('valorant', 'Valorant'), ('csgo', 'CS:GO'), ('apex', 'Apex Legends'), ('lol', 'League of Legends')], db_index=True, max_length=20)),
                ('rank', models.CharField(help_text='Game-specific rank (validated in serializer)', max_length=20)),
                ('vibe', models.CharField(choices=[('serious', 'Serious'), ('chill', 'Chill'), ('competitive', 'Competitive'), ('casual', 'Casual'), ('tryhard', 'Tryhard')], max_length=20)),
                ('mic_required', models.BooleanField(default=False)),
                ('max_participants', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('full', 'Full'), ('expired', 'Expired')], db_index=True, default='active', max_length=10)),
                ('region', models.CharField(blank=True, help_text='Server region (e.g., NA, EU, ASIA)', max_length=10)),
            ],
            options={
                'db_table': 'public_lobbies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['game', 'status', 'created_at'], name='public_lobb_game_b3dac9_idx'), models.Index(fields=['status', 'expires_at'], name='public_lobb_status_ba9469_idx')],
            },
        ),
        migrations.CreateModel(
            name='LobbyParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anon_token', models.CharField(db_index=True, help_text='SHA256(IP+UA+salt) for abuse prevention', max_length=64)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_fingerprint', models.CharField(blank=True, max_length=64)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='public_lobby.publiclobby')),
            ],
            options={
                'db_table': 'lobby_participants',
                'ordering': ['joined_at'],
                'constraints': [models.UniqueConstraint(fields=('lobby', 'anon_token'), name='unique_participant_per_lobby')],
            },
        ),
    ]
